<?php
use App\Modules\Auth\Presentation\Http\Controllers\AuthController;
use App\Modules\Catalog\Presentation\Http\Controllers\AttributeController;
use App\Modules\Catalog\Presentation\Http\Controllers\BrandController;
use App\Modules\Catalog\Presentation\Http\Controllers\CategoryController;
use App\Modules\Catalog\Presentation\Http\Controllers\ProductController;
use App\Modules\Customer\Presentation\Http\Controllers\CustomerController;
use App\Modules\Customer\Presentation\Http\Controllers\CustomerFeaturesController;
use App\Modules\Settings\Presentation\Http\Controllers\SettingsController;
use App\Modules\Staff\Presentation\Http\Controllers\StaffController;
use App\Modules\Inventory\Presentation\Http\Controllers\InventoryController;
use App\Modules\Order\Presentation\Http\Controllers\CheckoutController;
use App\Modules\Order\Presentation\Http\Controllers\OrderController;
use App\Modules\Payment\Presentation\Http\Controllers\PaymentController;
use App\Modules\Payment\Presentation\Http\Controllers\PaymobWebhookController;
use App\Modules\Payment\Presentation\Http\Controllers\KashierWebhookController;
use App\Modules\Payment\Presentation\Http\Controllers\OperationalDashboardController;
use App\Modules\Shipping\Presentation\Http\Controllers\ShippingController;
use App\Modules\Shipping\Presentation\Http\Controllers\BostaWebhookController;
use App\Modules\Promotion\Presentation\Http\Controllers\CouponController;
use App\Modules\Tax\Presentation\Http\Controllers\TaxRuleController;
use Illuminate\Support\Facades\Route;

Route::post('auth/register', [AuthController::class, 'register'])->middleware('guest')->name('auth.register');
Route::post('auth/login', [AuthController::class, 'login'])->middleware(['guest', 'throttle:auth-login'])->name('auth.login');
Route::post('webhooks/paymob', PaymobWebhookController::class)->name('webhooks.paymob');
Route::post('webhooks/kashier', KashierWebhookController::class)->name('webhooks.kashier');
Route::post('webhooks/bosta', BostaWebhookController::class)->name('webhooks.bosta');
Route::middleware('auth')->group(function () {
    Route::get('auth/me', [AuthController::class, 'me'])->name('auth.me');
    Route::post('auth/logout', [AuthController::class, 'logout'])->name('auth.logout');
    Route::post('auth/password', [AuthController::class, 'changePassword'])->name('auth.password');
    Route::get('staff', [StaffController::class, 'index'])->name('staff.index');
    Route::post('staff', [StaffController::class, 'store'])->name('staff.store');
    Route::match(['put', 'patch'], 'staff/{id}', [StaffController::class, 'update'])->name('staff.update');
    Route::delete('staff/{id}', [StaffController::class, 'destroy'])->name('staff.destroy');
    Route::get('inventory', [InventoryController::class, 'index'])->name('inventory.index');
    Route::post('inventory/adjust', [InventoryController::class, 'adjust'])->name('inventory.adjust');
    Route::post('inventory/reserve', [InventoryController::class, 'reserve'])->name('inventory.reserve');
    Route::post('inventory/release', [InventoryController::class, 'release'])->name('inventory.release');
    Route::get('customer/profile', [CustomerController::class, 'profile'])->name('customer.profile');
    Route::match(['put', 'patch'], 'customer/profile', [CustomerController::class, 'updateProfile'])->name('customer.profile.update');
    Route::get('customer/addresses', [CustomerFeaturesController::class, 'addresses'])->name('customer.addresses.index');
    Route::get('customer/addresses/default', [CustomerFeaturesController::class, 'defaultAddress'])->name('customer.addresses.default');
    Route::post('customer/addresses', [CustomerFeaturesController::class, 'addAddress'])->name('customer.addresses.store');
    Route::match(['put', 'patch'], 'customer/addresses/{id}', [CustomerFeaturesController::class, 'updateAddress'])->name('customer.addresses.update');
    Route::delete('customer/addresses/{id}', [CustomerFeaturesController::class, 'deleteAddress'])->name('customer.addresses.destroy');
    Route::get('customer/orders', [OrderController::class, 'customerIndex'])->name('customer.orders.index');
    Route::get('customer/orders/{id}', [OrderController::class, 'customerShow'])->name('customer.orders.show');
    Route::post('customer/orders/{id}/cancel', [OrderController::class, 'customerCancel'])->name('customer.orders.cancel');
    Route::post('customer/checkout', CheckoutController::class)->name('customer.checkout');
    Route::post('customer/orders/{orderId}/payments', [PaymentController::class, 'store'])->name('customer.payments.store');
    Route::get('customer/orders/{orderId}/payments', [PaymentController::class, 'index'])->name('customer.payments.index');
    Route::get('customer/shipping-methods', [ShippingController::class, 'customerMethods'])->name('customer.shipping-methods.index');
    Route::get('customer/orders/{orderId}/shipments', [ShippingController::class, 'customerShipments'])->name('customer.shipments.index');
    Route::post('customer/orders/{orderId}/shipments', [ShippingController::class, 'createShipment'])->name('customer.shipments.store');
    Route::get('customer/cart', [CustomerFeaturesController::class, 'cart'])->name('customer.cart.show');
    Route::post('customer/cart/items', [CustomerFeaturesController::class, 'addCartItem'])->name('customer.cart.items.store');
    Route::patch('customer/cart/items', [CustomerFeaturesController::class, 'updateCartItem'])->name('customer.cart.items.update');
    Route::delete('customer/cart', [CustomerFeaturesController::class, 'clearCart'])->name('customer.cart.clear');
    Route::delete('customer/cart/items/{productId}/{variantId?}', [CustomerFeaturesController::class, 'removeCartItem'])->name('customer.cart.items.destroy');
    Route::get('customer/wishlist', [CustomerFeaturesController::class, 'wishlist'])->name('customer.wishlist.index');
    Route::post('customer/wishlist', [CustomerFeaturesController::class, 'addWishlist'])->name('customer.wishlist.store');
    Route::delete('customer/wishlist/{productId}', [CustomerFeaturesController::class, 'removeWishlist'])->name('customer.wishlist.destroy');
    Route::get('customer/preferences', [CustomerFeaturesController::class, 'preferences'])->name('customer.preferences.show');
    Route::put('customer/preferences', [CustomerFeaturesController::class, 'updatePreferences'])->name('customer.preferences.update');
    Route::get('customer/notifications', [CustomerFeaturesController::class, 'notifications'])->name('customer.notifications.index');
    Route::patch('customer/notifications/{id}/read', [CustomerFeaturesController::class, 'readNotification'])->name('customer.notifications.read');
    Route::get('products', [ProductController::class, 'index'])->name('products.index');
    Route::post('products', [ProductController::class, 'store'])->name('products.store');
    Route::get('products/{product}', [ProductController::class, 'show'])->name('products.show');
    Route::match(['put', 'patch'], 'products/{product}', [ProductController::class, 'update'])->name('products.update');
    Route::delete('products/{product}', [ProductController::class, 'destroy'])->name('products.destroy');

    Route::get('products/{product}/variants', [ProductController::class, 'variants'])->name('products.variants.index');
    Route::post('products/{product}/variants', [ProductController::class, 'storeVariant'])->name('products.variants.store');
    Route::get('products/{product}/variants/{variant}', [ProductController::class, 'showVariant'])->name('products.variants.show');
    Route::match(['put', 'patch'], 'products/{product}/variants/{variant}', [ProductController::class, 'updateVariant'])->name('products.variants.update');
    Route::delete('products/{product}/variants/{variant}', [ProductController::class, 'destroyVariant'])->name('products.variants.destroy');

    Route::get('attributes', [AttributeController::class, 'index'])->name('attributes.index');
    Route::post('attributes', [AttributeController::class, 'store'])->name('attributes.store');
    Route::get('attributes/{attribute}', [AttributeController::class, 'show'])->name('attributes.show');
    Route::match(['put', 'patch'], 'attributes/{attribute}', [AttributeController::class, 'update'])->name('attributes.update');
    Route::delete('attributes/{attribute}', [AttributeController::class, 'destroy'])->name('attributes.destroy');

    Route::get('attributes/{attribute}/values', [AttributeController::class, 'values'])->name('attributes.values.index');
    Route::post('attributes/{attribute}/values', [AttributeController::class, 'storeValue'])->name('attributes.values.store');
    Route::get('attributes/{attribute}/values/{value}', [AttributeController::class, 'showValue'])->name('attributes.values.show');
    Route::match(['put', 'patch'], 'attributes/{attribute}/values/{value}', [AttributeController::class, 'updateValue'])->name('attributes.values.update');
    Route::delete('attributes/{attribute}/values/{value}', [AttributeController::class, 'destroyValue'])->name('attributes.values.destroy');

    Route::apiResource('brands', BrandController::class)->parameters(['brands' => 'id']);
    Route::apiResource('categories', CategoryController::class)->parameters(['categories' => 'id']);

    Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::get('settings/groups/{group}', [SettingsController::class, 'group'])->name('settings.group');
    Route::get('settings/{key}', [SettingsController::class, 'show'])->name('settings.show');
    Route::put('settings/{key?}', [SettingsController::class, 'update'])->name('settings.update');
    Route::get('orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('orders/{id}', [OrderController::class, 'show'])->name('orders.show');
    Route::patch('orders/{id}/status', [OrderController::class, 'updateStatus'])->name('orders.status');
    Route::post('orders/{id}/cancel', [OrderController::class, 'cancel'])->name('orders.cancel');
    Route::get('payments/orders/{orderId}', [PaymentController::class, 'adminIndex'])->name('payments.index');
    Route::get('operations/dashboard', OperationalDashboardController::class)->name('operations.dashboard');
    Route::post('payments/{paymentId}/confirm', [PaymentController::class, 'confirm'])->name('payments.confirm');
    Route::post('payments/{paymentId}/refund', [PaymentController::class, 'refund'])->name('payments.refund');
    Route::get('shipping-methods', [ShippingController::class, 'index'])->name('shipping-methods.index');
    Route::get('shipping-methods/{id}', [ShippingController::class, 'show'])->name('shipping-methods.show');
    Route::post('shipping-methods', [ShippingController::class, 'store'])->name('shipping-methods.store');
    Route::match(['put', 'patch'], 'shipping-methods/{id}', [ShippingController::class, 'update'])->name('shipping-methods.update');
    Route::delete('shipping-methods/{id}', [ShippingController::class, 'destroy'])->name('shipping-methods.destroy');
    Route::patch('shipments/{id}/status', [ShippingController::class, 'status'])->name('shipments.status');
    Route::apiResource('coupons', CouponController::class)->parameters(['coupons' => 'id']);
    Route::apiResource('tax-rules', TaxRuleController::class)->parameters(['tax-rules' => 'id']);
});
